repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      # Run the linter
      - id: ruff
        name: ruff
        entry: uv run --only-group lint dev/ruff.py
        language: system
        files: '\.(py|ipynb)$'
        stages: [pre-commit]
        require_serial: true

      # Run the formatter
      - id: format
        name: format
        entry: uv run --only-group lint dev/format.py
        language: system
        files: '\.(py|ipynb|md)$'
        stages: [pre-commit]
        require_serial: true

      # Run type checking
      - id: ty
        name: ty
        language: system
        files: |
          (?x)^(
            src/.*\.py|
            dev/.*\.py
           )$
        exclude: |
         (?x)^(
           src/.*/tests/.*\.py
          )$
        entry: uv run --only-group lint ty check --output-format github .
        require_serial: true

      - id: typos
        name: typos
        language: system
        entry: uv run --only-group typos typos
        args: []
        require_serial: true
