name: Build & Publish Science Package

on:
  push:
    tags:
      - "v*-science-package-*"

jobs:
  validate-tag:
    name: Validate tag and package version
    runs-on: ubuntu-latest

    outputs:
      package_name: ${{ steps.extract.outputs.package_name }}
      version: ${{ steps.extract.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Extract version and package name from tag
        id: extract
        run: |
          TAG="${GITHUB_REF#refs/tags/}"

          echo "Tag is: $TAG"

          # Regex: v<major>.<minor>.<patch>-science-package-<name>
          if [[ "$TAG" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)-science-package-(.+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            PACKAGE="${BASH_REMATCH[2]}"
          else
            echo "❌ Tag does not match expected pattern"
            exit 1
          fi

          echo "Extracted version: $VERSION"
          echo "Extracted package: $PACKAGE"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "package_name=$PACKAGE" >> $GITHUB_OUTPUT

  publish:
    name: Build & Publish to CodeArtifact
    runs-on: ubuntu-latest
    needs: validate-tag

    permissions:
      id-token: write   # required for OIDC
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.11"
          enable-cache: false

      - name: Build and publish package
        run: |
          VERSION="${{ needs.validate-tag.outputs.version }}"
          PACKAGE="${{ needs.validate-tag.outputs.package_name }}"

          echo "Update the version for package $PACKAGE to $VERSION"
          uv version --frozen --package "$PACKAGE" "$VERSION"

          echo "Building package: $PACKAGE"
          uv build --package "$PACKAGE"

          export UV_PUBLISH_USERNAME=aws

          export AWS_CODEARTIFACT_TOKEN="$(aws codeartifact get-authorization-token \
            --domain cognism \
            --domain-owner 321640139933 \
            --region eu-west-1 \
            --query authorizationToken \
            --output text)"

          export UV_PUBLISH_PASSWORD="$AWS_CODEARTIFACT_TOKEN"

          uv publish --index aws-code-artifactory
