name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    name: Tests (Pytest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.11"
          enable-cache: false
      - name: Install all packages and dependencies
        run: uv sync --locked --all-groups --all-packages
      - name: Test all packages
        run: |
          # Test all packages even if one package has changes to prove integration
          uv run pytest src/ -v
